### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ido555** [Storkman101/Void-World#1]

**Comment by Storkman101** [comment]
since you have only started the game just yet, what happens if you start another game?

**Comment by ido555** [comment]
The exact same 
here are some things i tried: 1 reinstalling this modpack
2. downloading the manually update version of this modpack
3. restarting my computer
4. one other thing i tried is to take everything in the chests and then died and i accidentally completed a quest which says i have to get these items but still no other quests and i couldn't find any NPCs

**Comment by Storkman101** [comment]
The thing that I miss in the video is that you open your book to the first quest line to see if there are any quests there. Because you get your first quests when you actually have teleported to the map itself and are out of the spawn area. Also the city quests will get the first quest when you have almost completed the first quest line (it is an bug that it is open at the start)

**Comment by ido555** [comment]
I still don't know why this is happening to me but i have found a solution i found some youtuber which uploads saves of his progress in this modpack and downloaded them and it works now. 
thank you though for trying to help me
