### ISSUE TITLE
HQM Quests, configuration problems

### ISSUE THREAD

**Issue by mycx** [Storkman101/Void-World#13]
@Storkman101 Hello Sir, Some of the quests are impossible to complete, since you messed up with some of the items xD
I'll try and list everything i found so far:

-"Technical > FluxDucts III" Can't complete the quest because you made it a crafting quest, and you selected the complete Redstone Energy Fluxduct, it can't be crafted, it's created in a fluid transposer, to fix this up, you should make it a 2 part quest, where in the first part you have to craft 64 Empty Redstone Energy Fluxducts and in the second part of the quest, a detection quest that requires 64 "Filled up" Fluxducts

-"Transmutation > Klein Star" The second part of the quest requires you to possess a Klein Star Omega, yet, right after crafting the Klein Star Ein for the first part of the quest, it automatically completes itself, maybe you messed up something with the MetaData, to fix this, make it a crafting quest.

-"Storage > Pure Certus" This quest is not completable too, since in the second part of the quest you selected, for the crafting quest, the 33% grown Certus Quartz Seed, and we can only craft the 0% grown one, fix that up :D Also, in the third part of the quest, after making us grow Pure Certus Quartz, the detection quest asks for Pure Nether Quartz (Not really sure if this was intentional)

-"Overall Knowledge > QED" I think that this quest's reward is kinda meaningless, i mean, to craft the QED you need a Diamond-Etched Computational Matrix, and to make that you need Burned Quartz, not a big problem, it's easy to make, but then after completing the quest Why would the reward be just 1 Burnt Quartz Block, maybe change it into a Greater/Good Reward Bag?

That's it for now, i'll keep adding more as i come across them (Had to recreate the world since i made my base in the Deep Dark and you removed it, hence i had to delete the world :P )

P.S.: The Modpack is awesome, it's one of my favourite modpacks ever ;D

**Comment by Storkman101** [comment]
- Every time I forget to change this -_-, I know it is a problem but I have forgotten it so many times now :P Sorry for that
  -With the crafting task you have the same problem. I had the problem before with the RF storage quests since they had the same problems. The kleinstar and the kleinstar omega both have the same ID but a different metadata, so atm it doesnt check for metadata so it does that. I have to check if the EMC storage is NBT data because there is an option to check metadata but not NBT data
  -Also found that one on the forum as well, the problem is that in the HQM book you can only select the 33% grown, but there I could not see the ...% grown so  I selected it but now I found out that it is bugged.
  -Yeah actually it makes sense, I should give it an higher reward like you said
  Most of these changes will likely be hitting the next patch which will be build tomorrow or the day after tomorrow, and will then be available for you guys to play. Thank you for submitting the bugs to me :D

About your base in the deep dark, were you mining there? I am interested to see
Also thank you for playing my pack and having fun with it, I love making people happy

**Comment by mycx** [comment]
Nope, i actually went there after a friend of mine suggested farming emc with a quarry there, but i never really entered the Deep Dark before so when i entered i thought it was freaking cool and before i could even think about setting up a quarry there i built a giant-ass colorfull Only Chisel house xD And i lived there like a shut-in with my beloved collectors Mk3 :p

**Comment by Storkman101** [comment]
That is why is disabled it, to prevent people with farming EMC with a quarry, and getting ores you shouldnt get. But LOL, always love the giant ass colorfull chisel houses, sadly for you you had to move out that house
