### ISSUE TITLE
Crash while loading

### ISSUE THREAD

**Issue by HCHexY** [Storkman101/Void-World#15]
It crashes before i get to the main menu
Crash report: http://pastebin.com/nQig3AQ2

**Comment by Storkman101** [comment]
Hey man, This probably has to do something by Java and not by my pack
You might want to search on the internet for java.lang.IndexOutOfBoundsException error since that is the problem. I can only help you by googling myself and I have other things to do so sorry man you have to see if you can figure out this yourself. If you dont plz tell me I dont want people that are not able to play my map

**Comment by darkrage000** [comment]
you are running Java 1.8
minecraft 1.7 and many mods have issues with Java 1.8 and up.  try downgrading or install a secondary version at java 1.7

**Comment by Storkman101** [comment]
A question, is this one fixed? Then I can close it and can keep the github page a bit clean :P
