### ISSUE TITLE
what is the point of the smeltry questline?

### ISSUE THREAD

**Issue by darkrage000** [Storkman101/Void-World#18]
you get a darkmatter pick in the bunker, so whats the point of the smeltry?  other than weapons and armor, dont need to make any tools.. but quest-line wants you to make picks and hammers and shovels..

**Comment by Storkman101** [comment]
I still have to work on that questline it will be expanded for sure but I keep pushing that project forward and forward. But indeed you get a dark matter pickaxe at the start. When I "update" the map(where you almost have to do a map reset) I will remove the dark matter pickaxe from the start and give you a tinkers pickaxe. But since I have to rebalance a bit when you will get stuff (like wood) I am more focused a bit on the AE questline atm then the Smeltery questline. But I hope this will answer your question

**Comment by darkrage000** [comment]
it does, thanks
