### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by Antillar** [Storkman101/Void-World#19]
1. Chapter Power Plant, quest Reactor. You need 13 yellorium fuel rods instead of 12 to finish the reactor.
2. Chapter Power Plant, quest Restoring the Reactor. You need at least 38 reactor casings instead of 35 and less than 85 reactor glass blocks instead of 125.
3. Chapter Technical, quest Automated Mob Farming, description line 4 word "can" should be replaced by "can't".
4. Chapter Storage, quest Pure Certus. In the third stage 20 Pure NETHER quartz is needed instead of 20 pure certus quartz, as it should be suggested by the quest name.
5. Obviously, I have picked both hardcore versions of the modpack in the beginning. Strikes vere in the beginning each hour, next every 30 minutes for quite a long time. After that, the following strike happened one minute after the previous one, as it finished, the message saying the new strike would be in 30 minutes appeared, but since that no strikes happened to me at all. I have a chat picture of the last strike, here it is: http://i.imgur.com/xxcWUIF.png

**Comment by Storkman101** [comment]
The first 3 I knew already because If I remember you already posted them into my forum post
4th, I messed something up again dammit. Still the quest can be finished so you will get the Charged certus which is needed to start up your system because you will need more but indeed this is a problem
5th Hmmm that is veeeeery strange. This will probably be fixed when I do a update on my redstone but like a said lately a couple of times that will be done later

**Comment by Antillar** [comment]
About 5th: strikes reappeared once I handed in day3 and day4 in Journal.
