### ISSUE TITLE
[Version: Recommended] Mob Hunter III

### ISSUE THREAD

**Issue by IcePenguin0898** [Storkman101/Void-World#29]
For some reason, I can't complete Mob Hunter III. I've killed at least 50 wither skeletons, and my progress hasn't gone up once. I've tried reloading my world, then restarting my game and my computer, and it hasn't fixed it.

**Comment by Storkman101** [comment]
Typed from my phone so sorry for the typing if I made any mistakes beforehand.
This is already fixed in V 1.1.4 but currently of you own a V 1.1.3(recommended) or lower world and open it in V 1.1.4 your world might crash and get corrupted. When I patch it and made a new version with that patch then it will be fixed

**Comment by Storkman101** [comment]
Soon V 1.1.5 will be available on the launcher (in around 45 minutes for manual download) with the 1.1.4 patch without the crashing. And that one will be set to recommended,then you can complete the missions I added/changed. So you can also complete Mob Hunter III, or Ritual Preparations called in the next version
