### ISSUE TITLE
Server world problem

### ISSUE THREAD

**Issue by TerminatorD47** [Storkman101/Void-World#36]
Im trying to run a server on the latest 1.1.7 VoidWorld pack and the world that comes in the server download is just a regular vanilla world and when i use a single player world on multiplayer the world is glitched and bugged out, blocks missing. How do i fix this or is there a legit server world download somewhere?

**Comment by TerminatorD47** [comment]
i can give server ip and show you if it helps

**Comment by Storkman101** [comment]
just a question, which file did you use to start the server. You have to use the ServerStart.bat to start the server otherwise it will not load the mods. If you ran the server with the minecraft_server.jar you have to download a new file and run the server through ServerStart.bat. Also you can allocate your RAM given to the server there when you edit the .bat file. Standard is set to allocate 1-2GB RAM for the server

**Comment by TerminatorD47** [comment]
I am renting a server and I never had this problem before I would always tell it to launch the Minecraft.jar its only this pack that does this. I have 2gb of RAM

**Comment by Storkman101** [comment]
Hmm I dont know. I just know that I had the same problem when this happened when I launched the normal minecraft 1.7.10.jar file and just get a normal vanilla world without any mods.

**Comment by TerminatorD47** [comment]
So there's no way to fix this

**Comment by Storkman101** [comment]
I think downloading a new file and use that files for the server if possible and then let it start through ServerStart.bat instead. 
And btw, the template folder in the server files is the map itself. In server.properties your world name should be template so it loads the map from the template folder

**Comment by TerminatorD47** [comment]
Ok i got it to work. The problem was when i transfer my single player world it got messed up. But when you said the world name is template that worked.
