### ISSUE TITLE
Nether still there?

### ISSUE THREAD

**Issue by Kuperus** [Storkman101/Void-World#38]
not sure if it is an issue or not, but when i entered the nether and hit J for map, on the edge i can see the former nether mapped out, is it in fact still there? can you slab to it? (if so that would allow big exploit)

furthermore not sure if it is meant to be, but you can use the map markers to teleport back and forth.

**Comment by Storkman101** [comment]
Yeah it actually is still there. When I started the map it started as something for me and my friends so I only removed a portion of the nether. I know you can teleport trough, but to get to that point you already have to be decently farm in the game so I don't mind as much currently. It is not a high priority bug

Verzonden vanuit Outlook Mobilehttps://aka.ms/blhgte

On Sun, Jan 24, 2016 at 12:52 PM -0800, "Kuperus" <notifications@github.com<mailto:notifications@github.com>> wrote:

not sure if it is an issue or not, but when i entered the nether and hit J for map, on the edge i can see the former nether mapped out, is it in fact still there? can you slab to it? (if so that would allow big exploit)

furthermore not sure if it is meant to be, but you can use the map markers to teleport back and forth

##

**Comment by Kuperus** [comment]
ehm, you can teleport from the start...
Journeymap features site to site transport capability....

set a point with waypoints and you can teleport to them.
p.s. waar woon je? :)

**Comment by Storkman101** [comment]
I know that is possible. But my highest priority of the last few days were fixing the issues around 1.1.9 and school. So now I can go start working on something else. And this might be one of them.
Btw BRABANT JONGUH

Verzonden vanuit Outlook Mobilehttps://aka.ms/blhgte

On Wed, Jan 27, 2016 at 12:53 PM -0800, "Kuperus" <notifications@github.com<mailto:notifications@github.com>> wrote:

ehm, you can teleport from the start...
Journeymap features site to site transport capability....

set a point with waypoints and you can teleport to them.
p.s. waar woon je? :)

##

**Comment by Kuperus** [comment]
Heh, ik ben import Hagenees :)...

btw for feathers: Briljant modpack
