### ISSUE TITLE
HQM Quests not completing. Few of them

### ISSUE THREAD

**Issue by Krisknows** [Storkman101/Void-World#7]
Ender Tech Quest - Had to HQM Edit for it

Pumpkins Moon-Moon Med Smile - HQM Edit

Charm of Life II - Don't know how to get more of them when there is no crafting recipe nor EMC

Klein Star Crafting Task Part 2 - Also not completing

Production quests for Liquids - Don't know why but isn't reading the water going in.

Hailey Quest screwed up somewhere Can't complete the Kill part Also the Jetpack Quest won't complete. I did it before the 1.0.2 but I never got the Jetpack Quest line (Funny because someone else got it and I'm already at max teir jetpack XD)

![jetpack 1](https://cloud.githubusercontent.com/assets/13261687/8605883/0bc50aa8-263d-11e5-9c11-51bccc68bb1f.png)
![jetpack 2](https://cloud.githubusercontent.com/assets/13261687/8605888/11cdd01a-263d-11e5-8a0b-3eb5ee47ee61.png)

So a few of them I had to HQM Edit to actually complete which i mentioned. Just wanted to know if there was any way to get the quests. (HQM Edit won't unlock them because I can't complete the Tuberous Jetpack)

**Comment by Krisknows** [comment]
Flux Ducts 3 Should also be a Detection quest not Crafting. Because it is impossible to craft them outside of using machinery which i can not get credit for

**Comment by Krisknows** [comment]
Automatic mob Farming does not read when you have a Zombie in your Safari Net

**Comment by Storkman101** [comment]
Sorrry for reacting so late, my email notifications on my phone got messed up and dont look on my pc email too often so I forgot to check the github sometimes. And since there were 2 messages I thought I had reacted to this one already sorry for this.
- which ender tech quest is not completing, I might know how to fix it already but I have to know. 
- will be fixed later when I update the map, that could take some time because I have to do that with my partner Spirit and he is gone on holiday and I will go on holiday when he comes back
  -fixed already
  -Will be fixed next patch, most likely will be build tomorrow or the day after tomorrow because then I have nothing to do that day
  -Have to have a look into that one, tried to fix it a couple of times but I still isnt fixed
  -Hmm, interesting that you cant complete it. Might have to make it a HQM quest then so it cant srew up anymore, but that will be fixed when I do a update which includes a map update since the NPC are generated with the world and will not be changed midway
  -Will be fixed next patch
  -Is fixed already

Thank you for playing my pack, and submitting the bugs to me
