### ISSUE TITLE
Will updating to a newer version of ProjectE affect anything?

### ISSUE THREAD

**Issue by Koncrete** [Storkman101/Void-World#9]
I ask because in the newer version they have tabs to make it easier to find items in the Transmutation Tablet.

**Comment by Krisknows** [comment]
If he does update to the new version of ProjectE he would have to redo all his EMC values again. So if he does AWESOME but if he doesn't I would understand because of all the EMC changes

**Comment by Storkman101** [comment]
Today I will start with the next patch of the pack which is only with modupdates for bugfixes for the mods itself and for more items. ProjectE will be one of them that is planned to be updated for sure. But thx for the headsup that all the EMC will be changed. Hopefully I can just copy the list with changed EMC and then paste it back in later when I have updated the mod

**Comment by Koncrete** [comment]
If there is anything I can do to help (manual number entries into a spreadsheet or anything mundane like that) please let me know.  This has become my favorite pack so far

**Comment by Storkman101** [comment]
Neh, I just finished with completely updating all mods that needed a update due to bugfixes that are relevant to the pack. I might start today with the normal bugfixing of the pack otherwise I will start tomorrow with that.
I am busy with making the EMC counts and minetweakerscripts back to how they were before the patch. Some scripts are changed or doesnt work. And it is really annoying to do if you do it with two persons (did it before with the co-maker of this pack) but that messed up and then some scripts got deleted
